=begin
Assignment 1:Basic Calculator
-------------
Create a method called “add” that accepts two numbers and adds them.
Your program should output the answer generated by your method to
the terminal.
=end

puts "Think of a number you would like to add?"
num1 = gets.chomp.to_i

puts "whats the second number to add?"
num2 = gets.chomp.to_i

added = (num1 + num2)

puts 'great, the number you are looking for is:'
puts added
